<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: balancer.proto

namespace App\Api;

/**
 * Generated from protobuf message <code>api.DisconnectResponse</code>
 */
class DisconnectResponse extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \App\GPBMetadata\Balancer::initOnce();
        parent::__construct($data);
    }

}

