<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: balancer.proto

namespace App\Api;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>api.DisconnectRequest</code>
 */
class DisconnectRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 serverNumber = 1;</code>
     */
    protected $serverNumber = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $serverNumber
     * }
     */
    public function __construct($data = NULL) {
        \App\GPBMetadata\Balancer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 serverNumber = 1;</code>
     * @return int
     */
    public function getServerNumber()
    {
        return $this->serverNumber;
    }

    /**
     * Generated from protobuf field <code>int32 serverNumber = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setServerNumber($var)
    {
        GPBUtil::checkInt32($var);
        $this->serverNumber = $var;

        return $this;
    }

}

