<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: balancer.proto

namespace App\Http\Controllers\Web\gen-grpc\Api;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>api.BalancerSetRequest</code>
 */
class BalancerSetRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string key = 1;</code>
     */
    protected $key = '';
    /**
     * Generated from protobuf field <code>string value = 2;</code>
     */
    protected $value = '';
    /**
     * Generated from protobuf field <code>int32 server = 3;</code>
     */
    protected $server = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $key
     *     @type string $value
     *     @type int $server
     * }
     */
    public function __construct($data = NULL) {
        grpc\GPBMetadata\Balancer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string key = 1;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>string key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string value = 2;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>string value = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 server = 3;</code>
     * @return int
     */
    public function getServer()
    {
        return $this->server;
    }

    /**
     * Generated from protobuf field <code>int32 server = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setServer($var)
    {
        GPBUtil::checkInt32($var);
        $this->server = $var;

        return $this;
    }

}

