<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: balancer.proto

namespace App\Http\Controllers\Web\gen-grpc\Api;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>api.ConnectRequest</code>
 */
class ConnectRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Address = 1;</code>
     */
    protected $Address = '';
    /**
     * Generated from protobuf field <code>uint64 Total = 2;</code>
     */
    protected $Total = 0;
    /**
     * Generated from protobuf field <code>uint64 Available = 3;</code>
     */
    protected $Available = 0;
    /**
     * Generated from protobuf field <code>int32 server = 4;</code>
     */
    protected $server = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Address
     *     @type int|string $Total
     *     @type int|string $Available
     *     @type int $server
     * }
     */
    public function __construct($data = NULL) {
        grpc\GPBMetadata\Balancer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string Address = 1;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->Address;
    }

    /**
     * Generated from protobuf field <code>string Address = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->Address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 Total = 2;</code>
     * @return int|string
     */
    public function getTotal()
    {
        return $this->Total;
    }

    /**
     * Generated from protobuf field <code>uint64 Total = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkUint64($var);
        $this->Total = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 Available = 3;</code>
     * @return int|string
     */
    public function getAvailable()
    {
        return $this->Available;
    }

    /**
     * Generated from protobuf field <code>uint64 Available = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAvailable($var)
    {
        GPBUtil::checkUint64($var);
        $this->Available = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 server = 4;</code>
     * @return int
     */
    public function getServer()
    {
        return $this->server;
    }

    /**
     * Generated from protobuf field <code>int32 server = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setServer($var)
    {
        GPBUtil::checkInt32($var);
        $this->server = $var;

        return $this;
    }

}

